## Capstone Data Wrangling with Sales Activity
### by Nicholas Sewitz

In this project I connect Artsy's redshift to pull in activity level data. We are pulling from tables, tasks (sales activity), site_landings, emails (marketing activity), and opportunities. The first 3 make up our features, and the last is where we get the output (and some demographic data). The goal of the analysis is to predict whether or not an opportunity will closed won, and what factors weigh most heavily in that decision. 

We have to do some wrangling to clean up and combine the features and outputs. For the activity features we create counts of the activities that happened before the opp closed. For the demographic features we create dummy variables.

Finally we output the data to a csv in both a MinMax scaled version and an original version.

In [1]:
import sys, os
sys.path.append(os.environ['minotaur'])

import yaml

%matplotlib inline
from matplotlib import pyplot as plt

import pandas as pd
import numpy as np
import patsy
import statsmodels.api as sm

from pylab import rcParams
rcParams['figure.figsize'] = 14,3
rcParams['font.family'] = 'Open Sans'

from dbs import redshift
redshift.connect()

from __future__ import division

from sklearn.preprocessing import PolynomialFeatures, MinMaxScaler
scaler = MinMaxScaler()

/usr/local/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [2]:
tasks = redshift.execute("""
SELECT t.activity_date,
       COALESCE(c.email,l.email) AS email,
       COALESCE(c.account_id,l.id) AS company_id,
       'sales' as source_table,
       t.type as activity_type,
       t.call_c as call_type
FROM segment_salesforce.tasks t
  LEFT JOIN segment_salesforce.contacts c
         ON t.who_id = c.id
        AND NOT c.is_deleted
  LEFT JOIN segment_salesforce.leads l
         ON t.who_id = l.id
        AND NOT l.is_deleted
WHERE NOT t.is_deleted AND (t.type = 'Email' OR t.type = 'Call')
""")
emails = redshift.execute("""
SELECT e.activity_date,
       p.email,
       p.company_id,
       'marketing' as source_table,
       'marketing_email' as activity_type,
       NULL as call_type
FROM marketo.email_delivers e
  INNER JOIN analytics.salesforce_patrons p ON e.lead_id = p.marketo_id
""")
opportunities = redshift.execute("""
SELECT o.id,
       o.account_id,
       o.stage_name,
       o.amount,
       o.created_date,
       o.close_date,
       o.abbreviated_channel_c,
       a.gallery_tier_c,
       a.sub_region_c
       FROM segment_salesforce.opportunities o 
           LEFT JOIN segment_salesforce.accounts a on o.account_id = a.id and not a.is_deleted
WHERE NOT o.is_deleted
AND   o.type = 'Activation'
AND (o.stage_name = 'Closed Won' OR o.stage_name = 'Closed Lost')
""")
site_landings = redshift.execute("""
SELECT sl.sent_at as activity_date,
       meam.email,
       sp.company_id,
       'site' as source_table,
       'site_visit' as activity_type,
       NULL as call_type
FROM analytics.site_landings sl
  INNER JOIN analytics.marketo_email_alias_mapping meam ON sl.looker_visitor_id = meam.looker_visitor_id
  INNER JOIN analytics.salesforce_patrons sp on meam.email = sp.email""")

In [3]:
#don't shorthand names
t = tasks
e = emails
sl = site_landings
o = opportunities

In [4]:
con = pd.concat([tasks,emails,site_landings],axis=0)

In [5]:
con.activity_type = con.activity_type.astype(str)
con.activity_type = con['activity_type'].apply(str.lower)
con.activity_type.unique()

array(['email', 'call', 'marketing_email', 'site_visit'], dtype=object)

In [6]:
con.call_type.unique()

array([None, 'No Answer', 'Not in Service', 'Connected', 'Wrong Number',
       'Left Voicemail', 'Busy', 'Rejected'], dtype=object)

will work with only 1 input

for activity_type, call_type in con:
    if call_type == 'Connected':
        con.activity_type = con.activity_type.replace('call', 'call_connect')
    elif call_type == 'Rejected':
        con.activity_type = con.activity_type.replace('call', 'call_reject')
        continue
con.activity_type.unique()

In [7]:
con.loc[con['call_type'] == 'Connected', 'activity_type'] = 'call_connect'
con.activity_type.unique()

array(['email', 'call', 'call_connect', 'marketing_email', 'site_visit'], dtype=object)

In [8]:
# trying to predict amount of time between activity and close. 
# trying to minimize time between activity and opportunity that is successful
# create dataset that combines site visits, emails, tasks with email address for each row
# add in opportunity
# sum up type by company_id and email

In [9]:
opps = pd.merge(con,opportunities,left_on='company_id',right_on='account_id',how='left')

In [10]:
opps.email.size

3080911

In [11]:
opps['activity_date'] = pd.to_datetime(opps['activity_date'])
opps['created_date'] = pd.to_datetime(opps['created_date'])
opps['close_date'] = pd.to_datetime(opps['close_date'])

In [12]:
opps['days'] = (opps.created_date - opps.activity_date).astype('timedelta64[D]')
opps['has_opp'] = ((opps.days <= 90) & (opps.days >= 0))
opps['has_inbound'] = opps.abbreviated_channel_c == 'Inbound'
opps['has_outbound'] = opps.abbreviated_channel_c == 'Outbound'
opps['has_inbound'] = opps['has_inbound'].astype(int)
opps['has_outbound'] = opps['has_outbound'].astype(int)

In [13]:
hops = opps[opps.has_opp == True].copy()
hops['company_opp'] = hops.company_id.map(str) + hops.id.map(str)
hops.head()

,activity_date,email,company_id,source_table,activity_type,call_type,id,account_id,stage_name,amount,created_date,close_date,abbreviated_channel_c,gallery_tier_c,sub_region_c,days,has_opp,has_inbound,has_outbound,company_opp
2,2017-07-17,nagwapicasso@yahoo.com,001C000001bcF3fIAE,sales,email,None,006C00000177zwsIAA,001C000001bcF3fIAE,Closed Lost,None,2017-07-17 13:01:41,2017-08-31,Inbound,4,Middle East,0.0,True,1,0,001C000001bcF3fIAE006C00000177zwsIAA
7,2017-07-17,nagwapicasso@yahoo.com,001C000001bcF3fIAE,sales,email,None,006C00000177zwsIAA,001C000001bcF3fIAE,Closed Lost,None,2017-07-17 13:01:41,2017-08-31,Inbound,4,Middle East,0.0,True,1,0,001C000001bcF3fIAE006C00000177zwsIAA
8,2017-08-07,yehkk285@gmail.com,001C000001QmZhyIAF,sales,email,None,006C00000179OQAIA2,001C000001QmZhyIAF,Closed Lost,None,2017-08-08 18:09:16,2017-09-23,Inbound,4,China,1.0,True,1,0,001C000001QmZhyIAF006C00000179OQAIA2
63,2017-07-07,info@brocketgallery.com,001C000001URy8RIAT,sales,email,None,006C0000016ZyC6IAK,001C000001URy8RIAT,Closed Won,5100.0,2017-07-07 15:09:49,2017-07-07,Outbound,4,United Kingdom,0.0,True,0,1,001C000001URy8RIAT006C0000016ZyC6IAK
81,2016-05-16,arlette@gallerykayafas.com,001C000001VmYEdIAN,sales,email,None,006C00000138ge7IAA,001C000001VmYEdIAN,Closed Lost,None,2016-05-19 18:50:20,2016-06-30,Outbound,4,US (New England),3.0,True,0,1,001C000001VmYEdIAN006C00000138ge7IAA

In [14]:
sub = hops[['company_opp','sub_region_c']].copy()
sub = sub.set_index('company_opp',drop=True)
sub = sub[~sub.index.duplicated(keep='last')]
sub = pd.get_dummies(sub,prefix='region')

In [15]:
tier = hops[['company_opp','gallery_tier_c']].copy()
tier = tier.set_index('company_opp',drop=True)
tier = tier[~tier.index.duplicated(keep='last')]
tier = pd.get_dummies(tier,prefix='tier')

In [16]:
company_opps = hops.company_opp.unique()
company_opps

array(['001C000001bcF3fIAE006C00000177zwsIAA',
       '001C000001QmZhyIAF006C00000179OQAIA2',
       '001C000001URy8RIAT006C0000016ZyC6IAK', ...,
       '001C0000012WVPJIA4006C00000115EdaIAE',
       '001C000001YM1jxIAD006C0000014oxgoIAA',
       '001C000001Qm8xlIAB006C0000010v0qzIAA'], dtype=object)

In [17]:
df = []
for company_opp in company_opps:
    d = dict(hops[hops.company_opp == company_opp].activity_type.value_counts())
    d['id'] = company_opp
    df += [d]
df = pd.DataFrame(df)

In [18]:
df = df.fillna(0)
df = df.set_index(['id'],drop=True)
dfnorm = pd.DataFrame(scaler.fit_transform(df), columns=df.columns,index=df.index)
dfnorm.head()

,call,call_connect,email,marketing_email,site_visit
id,,,,,
001C000001bcF3fIAE006C00000177zwsIAA,0.095238,0.066667,0.421053,0.004098,0.004386
001C000001QmZhyIAF006C00000179OQAIA2,0.142857,0.000000,0.157895,0.004098,0.000000
001C000001URy8RIAT006C0000016ZyC6IAK,0.047619,0.000000,0.157895,0.000000,0.008772
001C000001VmYEdIAN006C00000138ge7IAA,0.047619,0.000000,0.026316,0.000000,0.000000
001C000001HhnanIAB006C000000suCekIAE,0.095238,0.000000,0.131579,0.000000,0.000000

In [19]:
won = hops.set_index('company_opp',drop=True)
won['is_won'] = won.stage_name == 'Closed Won'
won.head()

,activity_date,email,company_id,source_table,activity_type,call_type,id,account_id,stage_name,amount,created_date,close_date,abbreviated_channel_c,gallery_tier_c,sub_region_c,days,has_opp,has_inbound,has_outbound,is_won
company_opp,,,,,,,,,,,,,,,,,,,,
001C000001bcF3fIAE006C00000177zwsIAA,2017-07-17,nagwapicasso@yahoo.com,001C000001bcF3fIAE,sales,email,None,006C00000177zwsIAA,001C000001bcF3fIAE,Closed Lost,None,2017-07-17 13:01:41,2017-08-31,Inbound,4,Middle East,0.0,True,1,0,False
001C000001bcF3fIAE006C00000177zwsIAA,2017-07-17,nagwapicasso@yahoo.com,001C000001bcF3fIAE,sales,email,None,006C00000177zwsIAA,001C000001bcF3fIAE,Closed Lost,None,2017-07-17 13:01:41,2017-08-31,Inbound,4,Middle East,0.0,True,1,0,False
001C000001QmZhyIAF006C00000179OQAIA2,2017-08-07,yehkk285@gmail.com,001C000001QmZhyIAF,sales,email,None,006C00000179OQAIA2,001C000001QmZhyIAF,Closed Lost,None,2017-08-08 18:09:16,2017-09-23,Inbound,4,China,1.0,True,1,0,False
001C000001URy8RIAT006C0000016ZyC6IAK,2017-07-07,info@brocketgallery.com,001C000001URy8RIAT,sales,email,None,006C0000016ZyC6IAK,001C000001URy8RIAT,Closed Won,5100.0,2017-07-07 15:09:49,2017-07-07,Outbound,4,United Kingdom,0.0,True,0,1,True
001C000001VmYEdIAN006C00000138ge7IAA,2016-05-16,arlette@gallerykayafas.com,001C000001VmYEdIAN,sales,email,None,006C00000138ge7IAA,001C000001VmYEdIAN,Closed Lost,None,2016-05-19 18:50:20,2016-06-30,Outbound,4,US (New England),3.0,True,0,1,False

In [20]:
won = won[['is_won']].copy()
won = won[~won.index.duplicated(keep='last')]
won.index.size

8195

In [21]:
chan = hops[['company_opp','has_inbound','has_outbound']].copy()
chan = chan.set_index('company_opp',drop=True)

In [22]:
finalnorm = dfnorm.join(won)
finalnorm = finalnorm.join(sub)
finalnorm = finalnorm.join(tier)
finalnorm = finalnorm.join(chan)
finalnorm = finalnorm[~finalnorm.index.duplicated(keep='last')]
print(finalnorm.shape)
finalnorm.head(10)

(8195, 52)

,call,call_connect,email,marketing_email,site_visit,is_won,region_Africa,region_Australia,region_Australia/New Zealand,region_Belgium,...,region_US (West Coast & Southwest),region_United Kingdom,region_Western Europe (France and Germany),tier_1,tier_2,tier_3,tier_4,tier_5,has_inbound,has_outbound
001C000000nUgF7IAK006C0000013XgDcIAK,0.047619,0.000000,0.000000,0.012295,0.000000,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
001C000000nUgF7IAK006C0000014LxSPIA0,0.285714,0.000000,0.289474,0.012295,0.000000,True,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
001C000000nUgF8IAK006C00000175waIIAQ,0.142857,0.066667,0.000000,0.036885,0.000000,False,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFAIA0006C000000ssBTQIA2,0.000000,0.000000,0.026316,0.000000,0.000000,True,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFBIA0006C0000011BPgIIAW,0.000000,0.000000,0.105263,0.000000,0.000000,False,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFBIA0006C0000015fCbFIAU,0.095238,0.000000,0.026316,0.180328,0.043860,False,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
001C000000nUgFEIA0006C000000wCD9LIAW,0.000000,0.000000,0.078947,0.000000,0.000000,False,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFEIA0006C0000014MrYEIA0,0.190476,0.000000,0.026316,0.032787,0.000000,True,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFHIA0006C0000012jlBTIAY,0.000000,0.000000,0.105263,0.036885,0.000000,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
001C000000nUgFHIA0006C0000016Y79TIAS,0.000000,0.066667,0.157895,0.020492,0.074561,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [23]:
finalnorm.to_csv('final_normalized.csv')

In [24]:
final = df.join(won)
final = final.join(sub)
final = final.join(tier)
final = final.join(chan)
final = final[~final.index.duplicated(keep='last')]
print(final.shape)
final.head(10)

(8195, 52)

,call,call_connect,email,marketing_email,site_visit,is_won,region_Africa,region_Australia,region_Australia/New Zealand,region_Belgium,...,region_US (West Coast & Southwest),region_United Kingdom,region_Western Europe (France and Germany),tier_1,tier_2,tier_3,tier_4,tier_5,has_inbound,has_outbound
001C000000nUgF7IAK006C0000013XgDcIAK,1.0,0.0,0.0,3.0,0.0,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
001C000000nUgF7IAK006C0000014LxSPIA0,6.0,0.0,11.0,3.0,0.0,True,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
001C000000nUgF8IAK006C00000175waIIAQ,3.0,1.0,0.0,9.0,0.0,False,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFAIA0006C000000ssBTQIA2,0.0,0.0,1.0,0.0,0.0,True,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFBIA0006C0000011BPgIIAW,0.0,0.0,4.0,0.0,0.0,False,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFBIA0006C0000015fCbFIAU,2.0,0.0,1.0,44.0,10.0,False,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
001C000000nUgFEIA0006C000000wCD9LIAW,0.0,0.0,3.0,0.0,0.0,False,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFEIA0006C0000014MrYEIA0,4.0,0.0,1.0,8.0,0.0,True,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
001C000000nUgFHIA0006C0000012jlBTIAY,0.0,0.0,4.0,9.0,0.0,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
001C000000nUgFHIA0006C0000016Y79TIAS,0.0,1.0,6.0,5.0,17.0,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [25]:
final.to_csv('final.csv')